import type { ReactNode } from 'react';
import React, { useEffect } from 'react';
import { CSSTransition, TransitionGroup } from 'react-transition-group';
import Head from 'next/head';
import { useRouter } from 'next/router';
import Sidebar from '@components/Sidebar';
import SidebarProvider from 'contexts/SidebarContext';

interface PropsInterface {
  children: ReactNode;
}

let isBack = false;

const AppLayout = ({ children }: PropsInterface) => {
  const router = useRouter();

  useEffect(() => {
    router.beforePopState((state) => {
      if (state.as !== router.asPath) {
        isBack = true;
      }
      return true;
    });

    return () => {
      isBack = false;
      router.beforePopState(() => true);
    };
  }, [router]);

  return (
    <SidebarProvider>
      <div style={{ height: '100vh' }}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Sidebar />
        <TransitionGroup
          childFactory={(child) =>
            React.cloneElement(child, {
              classNames: isBack ? 'left-to-right' : 'right-to-left',
              timeout: 300,
            })
          }
        >
          <CSSTransition key={router.pathname} classNames="right-to-left" timeout={300}>
            <div>{children}</div>
          </CSSTransition>
        </TransitionGroup>
      </div>
    </SidebarProvider>
  );
};

export default AppLayout;
